apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  template:
    spec:
      containers:
      - name: redpanda
        resources:
          # Memory limit set through unhelm; no CPU limit (slows everything down)
          limits:
            memory: 600Mi
          requests:
            cpu: 10m
            memory: 200Mi
