apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  template:
    spec:
      containers:
      - name: redpanda
        resources:
          # Note that limits are set through unhelm (kafka-v3/redpanda.kafka-v3.values.yaml)
          # and enforced at runtime through redpanda config
          requests:
            cpu: 10m
            memory: 330Mi
