apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  template:
    spec:
      containers:
      - name: redpanda
        resources:
          # unhelm sets requests=limits, but redpanda config only needs to match limits
          requests:
            cpu: 10m
            memory: 330Mi
