apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-exporter
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  podMetricsEndpoints:
  - port: web
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
