# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack
namePrefix: builds-registry-
resources:
- http://y-kustomize/v1/blobs/setup-bucket-job/base-for-annotations.yaml
commonAnnotations:
  yolean.se/bucket-name: ystack-builds-registry
