# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack
resources:
- y-kustomize.blobs.setup-bucket-job.yaml
- y-kustomize.kafka.setup-topic-job.yaml
