apiVersion: v1
kind: Service
metadata:
  name: buckety-controller-webhook
spec:
  selector:
    app.kubernetes.io/name: buckety-controller
  ports:
  - name: https
    port: 443
    targetPort: webhook
