apiVersion: v1
kind: Pod
metadata:
  name: buildkit-cached-builds
spec:
  containers:
  - name: build1
    image: builds-registry.ystack.svc.cluster.local/ystack-examples/buildkit-cache-1
  - name: build2
    image: builds-registry.ystack.svc.cluster.local/ystack-examples/buildkit-cache-2
  - name: build3
    image: builds-registry.ystack.svc.cluster.local/ystack-examples/buildkit-cache-3
  restartPolicy: Never
