apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-create-ystack-builds
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:RELEASE.2025-08-13T08-35-41Z
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        - name: BUCKET_NAME
          value: ystack-builds-registry
        - name: S3_ENDPOINT
          value: http://blobs-versitygw
        command:
        - sh
        - -ce
        - |
          until mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY 2>/dev/null; do
            sleep 2
          done
          mc mb --ignore-existing s3/$BUCKET_NAME
      restartPolicy: Never
  backoffLimit: 10
