# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../blobs-versitygw/defaultsecret
- ../generic
resources:
- bucket-create-ystack-builds.yaml
patchesStrategicMerge:
- deployment.yaml
