apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ystack
  labels:
    yolean.se/module-part: gateway
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    # Traefik helm chart's web entrypoint container port (exposed as 80 via Service)
    port: 8000
    allowedRoutes:
      namespaces:
        from: All
