apiVersion: v1
kind: Service
metadata:
  name: blobs-minio
  labels:
    app: minio
    release: blobs
spec:
  selector:
    app: minio
    release: blobs
  ports:
  - name: http
    port: 80
    targetPort: 9000
