apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- main-alertmanager-service.yaml
- main-alertmanager.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: alertmanager-main
  files:
  - alertmanager.yaml
