apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
- name: grafana/grafana
  newName: docker.io/grafana/grafana
  newTag: 10.2.3-ubuntu@sha256:d292a458726385a81fcf71c8fd4a67b6976f527585fc82cb6e24825d01c5797a
- name: grafana/grafana-image-renderer
  newName: docker.io/grafana/grafana-image-renderer
  newTag: 3.9.0@sha256:656ca4dddc020f067239428e2a15bc7100d8ce4918db1618b45d53d0c8c4d273

resources:
- grafana-service.yaml
- grafana-deployment.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  files:
  - prometheus-now.yaml=datasources-prometheus-now.yaml
  - loki.yaml=datasources-loki.yaml
- name: grafana-provisioning-dashboards
  files:
  - kubernetes-mixin.yaml=dashboards-kubernetes-mixin.yaml
  - imported.yaml=dashboards-imported.yaml
