apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
- name: grafana/grafana
  newName: docker.io/grafana/grafana
  newTag: 10.1.2-ubuntu@sha256:480ca6650f1ee46d8b8d204f2c629482eac39deaaae53d2b2b74ad84163c77f1
- name: grafana/grafana-image-renderer
  newName: docker.io/grafana/grafana-image-renderer
  newTag: 3.8.2@sha256:a46dace504b8c178e0b0f1edc5c4ebfb7436034cda4db35bbabfd862f7bb62de

resources:
- grafana-service.yaml
- grafana-deployment.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  files:
  - prometheus-now.yaml=datasources-prometheus-now.yaml
  - loki.yaml=datasources-loki.yaml
- name: grafana-provisioning-dashboards
  files:
  - kubernetes-mixin.yaml=dashboards-kubernetes-mixin.yaml
  - imported.yaml=dashboards-imported.yaml
