apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
- name: grafana/grafana
  newName: ghcr.io/yolean/grafana
  newTag: 11.1.4-ubuntu@sha256:8e74fb7eed4d59fb5595acd0576c21411167f6b6401426ae29f2e8f9f71b68f6
- name: grafana/grafana-image-renderer
  newName: ghcr.io/yolean/grafana-image-renderer
  newTag: 3.11.3@sha256:6de5a28a29328f972ed538b6172f07b2ff9204ee76c7f0bf32fd6da1d60956d4

resources:
- grafana-service.yaml
- grafana-deployment.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  files:
  - prometheus-now.yaml=datasources-prometheus-now.yaml
  - loki.yaml=datasources-loki.yaml
- name: grafana-provisioning-dashboards
  files:
  - kubernetes-mixin.yaml=dashboards-kubernetes-mixin.yaml
  - imported.yaml=dashboards-imported.yaml
