apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

images:
- name: grafana/grafana
  newName: ghcr.io/yolean/grafana
  newTag: 11.6.2-ubuntu@sha256:d4944c0571da5341a4d2d9d4068382fb655503887b2462497f599b3901b53d21
- name: grafana/grafana-image-renderer
  newName: ghcr.io/yolean/grafana-image-renderer
  newTag: 3.12.6@sha256:37d03fc58922f0a933a7a02e070e76ad8dc28bfb7a55c05ca898e01875fc8939

resources:
- grafana-service.yaml
- grafana-deployment.yaml

configMapGenerator:
- name: grafana-provisioning-datasources
  files:
  - prometheus-now.yaml=datasources-prometheus-now.yaml
  - loki.yaml=datasources-loki.yaml
- name: grafana-provisioning-dashboards
  files:
  - kubernetes-mixin.yaml=dashboards-kubernetes-mixin.yaml
  - imported.yaml=dashboards-imported.yaml
