apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: vectorized/redpanda
  newName: docker.io/vectorized/redpanda
  newTag: v23.3.1@sha256:faf973ac8097bcbe1ff34482b3d507e9036a7bf655c322f239145bc86891809f
