apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack
resources:
- ../../buildkit
- ../../buildkit/gateway-proxy
- ../../buildkit/grpcroute
- buildkitd-nodeport-service.yaml
patches:
- path: buildkitd-replicas-0.yaml
