apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../kube-state-metrics

patchesStrategicMerge:
- |-
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: kube-state-metrics
    namespace: kube-system
    labels:
      prometheus: now
