apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- ../kube-state-metrics

patchesStrategicMerge:
- |-
  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: kube-state-metrics
    namespace: kube-system
    labels:
      prometheus: now
# - |-
#   apiVersion: monitoring.coreos.com/v1
#   kind: PrometheusRule
#   metadata:
#     name: kube-state-metrics
#     labels:
#       prometheus: now
