# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack # install's app_url depends on namespace
resources:
- git-service.yaml
- gitea-statefulset-service.yaml
- gitea-statefulset.yaml
images:
- name: gitea/gitea
  newName: ghcr.io/yolean/gitea
  newTag: 1.25.4-rootless@sha256:1926e89ad28358ef2146bb8a1b9c3ba24bae681cb02b72d2df11125fdc675abe
