# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack # install's app_url depends on namespace
resources:
- git-service.yaml
- gitea-statefulset-service.yaml
- gitea-statefulset.yaml
images:
- name: gitea/gitea
  newName: ghcr.io/yolean/gitea
  newTag: 1.26.2-rootless@sha256:c5c21a7705a16f2b2369384a3b7d67c5ed761a818bbb0a55187b5cf98cdc2e68
