secretGenerator:
- name: y-kustomize.blobs.setup-bucket-job
  options:
    disableNameSuffixHash: true
  files:
  - base-for-annotations.yaml=y-kustomize-bases/blobs/setup-bucket-job/base-for-annotations.yaml
