# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker:dind
  newName: ghcr.io/yolean/dockerd
  newTag: 29.4.1-dind@sha256:c77e5d7912f9b137cc67051fdc2991d8f5ae22c55ddf532bb836dcb693a04940
- name: docker:dind-rootless
  newName: ghcr.io/yolean/dockerd
  newTag: 29.4.1-dind-rootless@sha256:b195ea3784d101abfe1ac68a47f95bcde74bb7ea4e4e8d277d29bc2661a6ae0e

resources:
- dockerd-service.yaml
- dockerd-statefulset.yaml

configMapGenerator:
- name: etc-docker
  files:
  - daemon.json
