apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- release.yaml

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: tekton-pipelines-controller
  # Note: the args list may change at Tekton upgrade; verify that the debug-nonroot image comes after the -shell-image arg
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/15
      value: gcr.io/distroless/base:debug-nonroot@sha256:868b149a21379205ef3ec237cf8a0c2f30468405829b5fef0b29cc724fe7f34c

# To override config add config maps like:
# configMapGenerator:
# - name: config-artifact-bucket
#   literals:
#   - location=gs://my-actual-bucket
#   options:
#     disableNameSuffixHash: true
#     labels:
#       app.kubernetes.io/instance: default
#       app.kubernetes.io/part-of: tekton-pipelines
#   namespace: tekton-pipelines
#   behavior: replace
