# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Produces a Secret y-kustomize.blobs.setup-bucket-job whose data key
# base-for-annotations.yaml is a Job spec for s3 bucket setup.
# y-cluster serve picks up this Secret and serves it at
# /v1/blobs/setup-bucket-job/base-for-annotations.yaml.
secretGenerator:
- name: y-kustomize.blobs.setup-bucket-job
  options:
    disableNameSuffixHash: true
    labels:
      yolean.se/module-part: y-kustomize
  files:
  - base-for-annotations.yaml
