# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ONLY_apply_through_cluster_variant

resources:
- ../base
