apiVersion: v1
kind: Service
metadata:
  name: thanos-query
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: thanos-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - query
        - --http-address=0.0.0.0:9090
        - --endpoint=thanos-receive.monitoring.svc.cluster.local:10901
        ports:
        - name: http
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
          initialDelaySeconds: 15
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 256Mi
