apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    spec:
      containers:
      - name: docker-v2
        readinessProbe:
          httpGet:
            path: /debug/health
            port: 5001
            scheme: HTTP
