apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-kustomize
  labels:
    app: y-kustomize
    yolean.se/module-part: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: y-kustomize
  template:
    metadata:
      labels:
        app: y-kustomize
    spec:
      serviceAccountName: y-kustomize
      containers:
      - name: y-kustomize
        image: ghcr.io/yolean/y-kustomize:latest
        ports:
        - containerPort: 8787
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8787
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 32Mi
