apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-kustomize
  labels:
    app: y-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: y-kustomize
  template:
    metadata:
      labels:
        app: y-kustomize
    spec:
      serviceAccountName: y-kustomize
      containers:
      - name: y-kustomize
        image: ghcr.io/yolean/y-kustomize:c55953b69f74067043f2351f8727ea84db1737ca@sha256:e44f99f6bbae59aef485610402c8f3f0125e197fff8616643bd4d5c65ce619e1
        ports:
        - containerPort: 8787
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8787
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            memory: 32Mi
