apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ystack-installer-knative-cluster-admin
subjects:
- kind: ServiceAccount
  name: ystack-installer-knative
  #namespace: #set through Kustomize base's namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
