apiVersion: v1
kind: Service
metadata:
  name: monitoring-nodeport
  labels:
    ystack-kubefwd: never
spec:
  type: NodePort
  selector:
    app: monitoring-proxy
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31710
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 31711
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31712
