apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: y-kustomize
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: ghcr.io/yolean/y-kustomize
    context: .
    custom:
      buildCommand: |
        set -e
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags='-s -w' -o target/linux/amd64/y-kustomize . &&
        PLATFORMS=linux/amd64 IMAGE=$IMAGE y-contain build --push=false --tarball target-oci/y-kustomize.tar --platforms-env-require &&
        cat target-oci/y-kustomize.tar | y-cluster-local-ctr -n k8s.io images import --digests -
      dependencies:
        paths:
        - "**/*.go"
        - contain.yaml
        - go.mod
        - go.sum
  local:
    push: false
    useBuildkit: false
deploy:
  kubectl:
    defaultNamespace: ystack
    hooks:
      after:
      - host:
          command: ["sh", "-c", "kubectl --context=local -n ystack rollout restart deploy/y-kustomize"]
