apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: y-kustomize
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: ghcr.io/yolean/y-kustomize
    context: .
    custom:
      buildCommand: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags='-s -w' -o target/linux/amd64/y-kustomize . &&
        y-contain build --push=false --output target-oci --format oci
      dependencies:
        paths:
        - "**/*.go"
        - contain.yaml
        - go.mod
        - go.sum
  local:
    push: false
