# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack

images:
- name: moby/buildkit:rootless
  newName: ghcr.io/yolean/buildkit
  newTag: v0.30.0-rootless@sha256:d76eb1caecac5733ef7553c1e90a1b21f1bb218cd1142d3553de0747b4a14ba9

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
