# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack

images:
- name: moby/buildkit:rootless
  newName: ghcr.io/yolean/buildkit
  newTag: v0.31.1-rootless@sha256:946cf909534b789c9b84af75e6d4f8cb23c3b9cb387daec5ba0f4878a3e4647c

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
