# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ystack

images:
- name: moby/buildkit:rootless
  newName: ghcr.io/yolean/buildkit
  newTag: v0.28.0-rootless@sha256:0add53e4362ff54ab59f0d4ef78b0397ed23ee8e2d0366f9b9c3c67575c7c9ef

resources:
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: etc-buildkit
  files:
  - buildkitd.toml
