# https://github.com/moby/buildkit/blob/master/examples/kube-consistent-hash/buildkitd-rootless-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: buildkitd
    status: accepts-new-builds
  name: buildkitd
spec:
  serviceName: buildkitd
  replicas: 2
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
# see buildkit/docs/rootless.md for caveats of rootless mode
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:v0.6.2-rootless@sha256:aac5b5f0341999e7ebeb041e4709554822d60b99674cd6cb491e6f1a2cfd08ab
        args:
        - --addr
        - unix:///run/user/1000/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:8547
        - --oci-worker-no-process-sandbox
        ports:
        - containerPort: 8547
        volumeMounts:
        - name: etc-buildkit
          mountPath: /home/user/.config/buildkit
      volumes:
      - name: etc-buildkit
        configMap:
          name: etc-buildkit
