apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-webhook
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info

    [INPUT]
        Name              http
        Listen            0.0.0.0
        Port              9880
        Tag               gitea
        buffer_max_size   1M
        buffer_chunk_size 64K

    [OUTPUT]
        Name                s3
        Match               *
        region              us-east-1
        bucket              gitea-events
        endpoint            http://blobs-versitygw.ystack.svc.cluster.local
        s3_key_format       /events/%Y/%m/%d/%H%M%S/$UUID.json
        use_put_object      On
        upload_timeout      15s
        total_file_size     1M
        store_dir           /tmp/fluent-bit/s3
        tls                 Off
