apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-webhook
  labels:
    app: fluentbit-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentbit-webhook
  template:
    metadata:
      labels:
        app: fluentbit-webhook
    spec:
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:4.0
        ports:
        - containerPort: 9880
          name: http
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: buffer
          mountPath: /tmp/fluent-bit/s3
      volumes:
      - name: config
        configMap:
          name: fluentbit-webhook
      - name: buffer
        emptyDir: {}
