apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: in-cluster-build
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local:80/ystack-examples/example-server
    sync:
      infer: ["**/*"]
    kaniko:
      reproducible: true
  cluster: {}
deploy:
  kubectl:
    manifests:
    - k8s/example-server-deployment.yaml
    - k8s/example-server-service.yaml
