resources:
- blobs-versitygw-service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: y-kustomize.blobs.setup-bucket-job
  files:
  - kustomization.yaml=y-kustomize-bases/blobs/setup-bucket-job/kustomization.yaml
  - setup-bucket-job.yaml=y-kustomize-bases/blobs/setup-bucket-job/setup-bucket-job.yaml
