apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-ip
  labels:
    app: node-ip
spec:
  selector:
    matchLabels:
      app: node-ip
  template:
    metadata:
      labels:
        app: node-ip
    spec:
      hostNetwork: true
      containers:
      - name: pause
        image: gcr.io/google_containers/pause-amd64:3.1@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610
