# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blobs
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: minio
  literals:
  - accesskey=YstackEXAMPLEKEY
  - secretkey=github.com/Yolean/ystack-EXAMPLE
