# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../registry/prod-service
patches:
- path: prod-registry-magic-numbers.yaml
