# yaml-language-server: $schema=https://github.com/redpanda-data/helm-charts/raw/redpanda-5.6.60/charts/redpanda/values.schema.json
# unhelm-template-repo: https://charts.redpanda.com
# unhelm-namespace: kafka

# this is an attempt to disable as much as possible from the chart, except the actual broker
statefulset:
  replicas: 1
  sideCars:
    configWatcher:
      enabled: false
resources:
  cpu:
    cores: 250m
    overprovisioned: true
  memory:
    container:
      max: 1124Mi
    redpanda:
      memory: 1024Mi
      reserveMemory: 100Mi
config:
  cluster:
    # Note: apply might not affect actual cluster config, check with
    # rpk cluster config --api-urls redpanda.kafka:9644 get
    auto_create_topics_enabled: false
    default_topic_replications: 1
    default_topic_partitions: 1
    storage_min_free_bytes: 104857600
tls:
  enabled: false
external:
  enabled: false
rbac:
  enabled: false
post_install_job:
  enabled: false
post_upgrade_job:
  enabled: false
console:
  enabled: false
logging:
  logLevel: info
  usageStats:
    enabled: false
tuning:
  tune_aio_events: false
# See forwarded ports in ../k3s/ystack.yaml
# See also https://github.com/redpanda-data/helm-charts/issues/285
listeners:
  kafka:
    port: 9092
    external:
      default:
        advertisedPorts:
        - 31712
  http:
    port: 8082
    external:
      default:
        advertisedPorts:
        - 31713
