# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../monitoring/prometheus-now
- ../../monitoring/alertmanager-main
- ../../monitoring/kube-state-metrics-now
- ../../monitoring/node-exporter-now
- ../../monitoring/httproute
