apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ../node-exporter

patchesStrategicMerge:
- |-
  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: node-exporter
    labels:
      prometheus: now
- |-
  apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    name: node-exporter
    labels:
      prometheus: now
