apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    # all examples have this: nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: builds-registry.ystack.svc.cluster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: builds-registry
          servicePort: 80
