apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-create-ystack-builds
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:RELEASE.2025-08-13T08-35-41Z
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        - name: MINIO_HOST
          value: http://blobs-minio
        - name: MINIO_REGION
          value: us-east-1
        - name: BUCKET_NAME
          value: ystack-builds-registry
        command:
        - sh
        - -ce
        - |
          until mc alias set ystack "$MINIO_HOST" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY"; do
            echo "Waiting for minio..."
            sleep 5
          done
          mc stat ystack/$BUCKET_NAME || {
            mc mb --region="$MINIO_REGION" ystack/$BUCKET_NAME
          }
      restartPolicy: Never
  backoffLimit: 10
