apiVersion: batch/v1
kind: Job
metadata:
  name: bucket-create-ystack-builds
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:RELEASE.2019-10-09T22-54-57Z@sha256:cfa18a5564f7649080792212d0a9281b60b1a732ef329877f56fc108cee5f012
        env:
        - name: MINIO_HOST
          value: http://blobs-minio
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: blobs-minio
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: blobs-minio
              key: secretkey
        - name: MINIO_REGION
          value: us-east-1
        - name: BUCKET_NAME
          # TODO all from secret, except host maybe
          value: ystack-builds-registry
        command:
        - sh
        - -ce
        - |
          mc config host add ystack $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          mc stat ystack/$BUCKET_NAME || {
            mc mb --region="$MINIO_REGION" ystack/$BUCKET_NAME
          }
      restartPolicy: Never
  backoffLimit: 10
