apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  template:
    spec:
      containers:
      - name: docker-v2
        env:
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: blobs-minio
              key: accesskey
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: blobs-minio
              key: secretkey
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: http://blobs-minio.ystack.svc.cluster.local
        - name: REGISTRY_STORAGE_S3_REGION
          value: us-east-1
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: ystack-builds-registry
        - name: REGISTRY_STORAGE_REDIRECT_DISABLE
          value: "true"
