apiVersion: v1
kind: Namespace
metadata:
  name: ystack
---
apiVersion: v1
kind: Namespace
metadata:
  name: blobs
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
