apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  selector:
    app: monitoring-proxy
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
