apiVersion: skaffold/v3
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/ystack-examples/node-backend
    context: backend
    custom:
      buildCommand: y-build-exists || y-build
      dependencies:
        dockerfile:
          path: ./Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
