apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    useBuildkit: true
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/ystack-examples/node-backend
    context: backend
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: 'src/**/*.js'
        dest: .
