apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/ystack-examples/node-backend
    context: backend
    custom:
      buildCommand: y-build
      dependencies:
        dockerfile:
          path: ./Dockerfile
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: 'src/**/*.js'
        dest: .
